### ISSUE TITLE
How married to the name are you?

### ISSUE THREAD

**Issue by kescobo** [a-poor/QuickAPI.jl#1]
Hello! I just started to work on [_my_ Hapi.jl](https://github.com/kescobo/Hapi.jl), and I stumbled on this. I'm quite attached to the name, though obviously there's no such thing as dibs in software :stuck_out_tongue:. And in any case, I've let it languish for so long that I don't really have a claim, but I thought it might be nice to work it out before either of us gets too far in the development process

**Comment by a-poor** [comment]
Hey! No worries, the name is yours. Good luck with your project -- seems like a great idea.

**Comment by kescobo** [comment]
Thank you!
